name: fetch_app_logs
description: Fetch all of the logs produced by the application
  during its execution
version: 0.0.2
homepage: https://gitjournal.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.gitjournal.fetch_app_logs
    pluginClass: FetchAppLogsPlugin
